name: Survyvaller
author: 7kasper
version: 0.1
main: survyvaller.Survyvaller
commands:
  admin:
    description: Toggles adminmode.
    usage: /<command>
    permission: survyaller.admin
    permission-message: You're no admin!
  tell:
    description: Private message other player.
    usage: /<command> <player> <msg...>
    permission: survyvaller.default
    permission-message: You can't do that!
    aliases: [msg, t]
  reply:
    description: Reply to a private message.
    usage: /<command> <msg...>
    permission: survyvaller.default
    permission-message: You can't do that!
    aliases: [respond, r]
  rank:
    description: Show or alter player's rank.
    usage: /<command> <player> <rank>
    permission: survyvaller.admin
    permission-message: You can't do that!
  report:
    description: Reports a report.
    usage: /<command> <report>
    permission: survyvaller.helper
    permission-message: You can't do that!
  reports:
    description: View or teleport to reports.
    usage: /<command> (page / view) (reportnum)
    permission: survyvaller.admin
    permission-message: You can't do that!
    
permissions:
  survyvaller.default:
    description: Gives access to survyvaller's default commands & things.
    default: true
  survyvaller.helper:
    description: Gives access to survyvaller's helper commands & things.
    default: true
  survyvaller.admin:
    description: Gives access to survyvaller's admin commands & things.
    default: true